### ISSUE TITLE
Striking a wall or floor has no effect

### ISSUE THREAD

**Issue by abraini-Nascent** [hankmorgan/Underworld-Exporter-Scene#36]
https://github.com/hankmorgan/Underworld-Exporter-Scene/blob/ce85b3a64eb1c04456f6cc59a2202cc335089dc8/Assets/scripts/Combat/UWCombat.cs#L174

I haven't tested in the game but I've been reading through the source and this seems off.
`Random.Range(1, durability + 1) - durability`
`rand(1 - 21) - 20` will be negative or 0
then we clamp to 0

maybe this was meant to be a placeholder?

**Comment by hankmorgan** [comment]
The mathf.max(0, calculation) will clamp to 0
